spring.application.name=todo-managemnet
spring.datasource.url=jdbc:mysql://localhost:3306/todo_management
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

app.jwt-secret=bf9b7a0ea091ee979b10c78945e5fbfd0b1a2411e0c0f2c61ed47d74229aade2
app.jwt-expiration-milliseconds=604800000